- label: "JIRA"
  message: "$issuePrefix"
  icon: "jira"
  color: "blue"
  url: "https://jira.company.com/browse/$issuePrefix"
  when: "$issuePrefix"

- message: "$author"
  color: "green"

- message: "Work in Progress"
  color: "yellow"
  when: "$payload.pull_request.title.includes('WIP')"

- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions >= 500"

- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions > 200 && $additions < 500"

- label: "Passed"
  message: "QA"
  color: green
  when: "$payload.pull_request.body.includes('- [x] QA')"

- message: "Contributor"
  color: "#000000"
  when: "$payload.pull_request.author_association == 'CONTRIBUTOR'"

- label: "Label"
  message: "Feature"
  when: "$labels.includes('Feature')"

- label: "Label"
  message: "Fix"
  when: "$labels.includes('Fix')"

- label: "Label"
  message: "Task"
  when: "$labels.includes('Task')"

- label: "Draft"
  message: "Draft"
  color: "lightgrey"
  when: "$payload.pullrequest.draft"

- label: "Closed"
  message: "Closed"
  color: "gray"