PROJECT_NAME="HulajDusza_serwis"
PROJECT_VERSION="1.0.0"
RELEASE="enabled"
RETENTION_DAYS="1"
TESTING="enabled"
SONAR="enabled"
JAVA_VERSION="8"
NODE_VERSION="20"
NODE_DIST_DIR="./"
JAVA_DIST_DIR="./"
JAVA_DISTRIBUTION="temurin"