PROJECT_NAME="HulajDusza_serwis"
PROJECT_VERSION="0.5.0"
RELEASE="enabled"
RETENTION_DAYS="1"
TESTING="enabled"
SONAR="disabled"
JAVA_VERSION="8"
PYTHON_VERSION="3.10"
NODE_VERSION="18"
NODE_DIST_DIR="public_html/"
PYTHON_DIST_DIR="./"
JAVA_DIST_DIR="public_html/js"
JAVA_DISTRIBUTION="temurin"
RUBY_VERSION="YOUR_RUBY_VERSION"
GO_VERSION="YOUR_GO_VERSION"
DOCKER_TAG="latest"
DOCKER_REPOSITORY="YOUR_DOCKER_REPOSITORY"
AWS_S3_BUCKET_NAME="YOUR_AWS_S3_BUCKET_NAME"
AWS_REGION="eu-north-1"
AWS_ECR_REGISTRY="000000000000.dkr.ecr.REGION.amazonaws.com"
AWS_ECR_REPOSITORY="YOUR_REPOSITORY_NAME"