version = 1

test_patterns = [
  "**/__tests__/**",
  "**/*.spec.ts",
  "**/*.spec.js",
  "**/*.test.ts",
  "**/*.test.js"
]

exclude_patterns = [
  "node_modules",
  "bower_components",
  "out",
  "bin",
  "build",
  "dist",
  "public_html"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "jquery",
    "browser"
  ]
  module_system = "es-modules"
  dialect = "flow"

[[analyzers]]
name = "php"

[[transformers]]
name = "prettier"

[[analyzers]]
name = "test-coverage"
enabled = true