name: Run Gulp Task

# Workflow będzie uruchamiany na wydarzeniach push
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest  # Środowisko, w którym będzie wykonywany build
    
    steps:
    - name: Honeybadger Deploy Action
      uses: honeybadger-io/github-notify-deploy-action@v1
            
    - name: Checkout code  # Krok do pobrania kodu repozytorium
      uses: actions/checkout@v4

    - name: Setup Node.js  # Krok do instalacji Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Wybór wersji Node.js, którą chcesz zainstalować

    - name: Install dependencies  # Instalowanie zależności
      run: npm install

    - name: Run Gulp Task  # Uruchomienie zadania npm run gulp
      run: npm run gulp

    - name: Configure Git  # Konfiguracja git, żeby móc commitować zmiany
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Commit changes  # Commitowanie zmian
      run: |
        git add .
        git commit -m "Automated Gulp build changes"
      continue-on-error: true  # Pozwala uniknąć błędu, jeśli nie ma nic do commitowania

    - name: Push changes  # Wypychanie zmian do repozytorium
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Użycie tokenu GitHub do autoryzacji push