name: Label Pull Requests

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Label to add'
        required: true

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add label to pull requests
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: $pr
