name: Label Previous Pull Requests

on:
  workflow_dispatch:
  pull_request:
    types:
      - unlabeled
jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add label to pull requests
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.unlabeled }}
